name: Release Electron App

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  windows:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build Windows
        env:
          ELECTRON_MIRROR: https://npmmirror.com/mirrors/electron/
        run: npm run dist

      - name: Upload Windows Artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-build
          path: dist/*.exe

  mac:
    runs-on: macos-latest
    needs: windows

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Download Windows Artifact
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: actions/download-artifact@v4
        with:
          name: windows-build
          path: dist

      - name: Build and Publish macOS
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ELECTRON_MIRROR: https://npmmirror.com/mirrors/electron/
        run: npm run release